version: "3"
services:
  client:
    build:
      context: ./netprune_client
      dockerfile: client.DockerFile
    ports:
      - 3000:3000
  netprune:
    build:
      context: ./netprune_server
      dockerfile: netprune.DockerFile
    volumes:
      - ./netprune_server:/server
    ports:
      - 5000:5000
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017