version: "3"
services:
  netprune:
    build:
      context: .
      dockerfile: netprune.DockerFile
    volumes:
      - .:/server
    ports:
      - 5000:5000
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017